name: Deploy to Kubernetes

on:
  push:
    branches: [ no_deploy ]
    paths-ignore:
          - 'README.md'
          - '.gitignore'
          - '.gitattributes'
          - 'LICENSE'

jobs:
  build-infra:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials via OIDC (Terraform)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.TERRAFORM_ROLE_ARN }}
          aws-region: us-east-1

      - name: Deploy Kubernetes Cluster
        working-directory: ./terraform
        run: |
          terraform init
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan

  docker:
    runs-on: ubuntu-latest
    needs: build-infra

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ secrets.DOCKERHUB_USER }}/${{ secrets.IMAGE_NAME }}:latest ./app

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login ghcr.io -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

      - name: Push image
        run: docker push ghcr.io/${{ secrets.DOCKERHUB_USER }}/kubefleet:latest
